절차서NO: ${wkProc.wkProcNo!}
<br><br>
작업구분 : ${wkProc.wkKindNm!}
<br><br>
보충작업구분: ${wkProc.wkSuppKindNm!}
<br><br>
작업명칭: ${wkProc.wkNm!}
<br><br>
작업일: ${wkProc.wkYmd!}
<br><br>
작업시간: ${wkProc.workTime!}
<br><br>
시행부서/부서담당 : ${wkProc.enfDeptNm!} / ${wkProc.enfDeptRespUserNm!}
<br><br>
사전검토 후 승인요청한 작업허가서가 승인되었으며, 해당 작업허가서의 수시점검자로 지정되었습니다.
<br><br>
아래 바로 가기를 클릭하여 해당 승인된 작업허가서를 확인하고, 작업중에 수시점검 후 수시점검결과를 등록하시기 바랍니다.
