절차서NO: ${wkProc.wkProcNo!}
<br><br>
작업구분 : ${wkProc.wkKindNm!}
<br><br>
보충작업구분: ${wkProc.wkSuppKindNm!}
<br><br>
작업명칭: ${wkProc.wkNm!}
<br><br>
작업일: ${wkProc.wkYmd!}
<br><br>
작업시간: ${wkProc.workTime!}
<br><br>
연장작업시간: ${wkProc.overRqstTime!}
<br><br>
시행부서/부서담당 : ${wkProc.enfDeptNm!} / ${wkProc.enfDeptRespUserNm!}
<br><br>
연장 승인요청한 작업허가서가 반려되었습니다.
<br><br>
아래 바로 가기를 클릭하여 해당 반려된 작업허가서를 확인하고, 보완 후 다시 연장 승인요청하시기 바랍니다.