신청부서/신청자: ${judge.rqstDeptNm!} / ${judge.rqstUserNm!}
<br><br>
신청일: ${judge.rqstYmd!}
<br><br>
공사명(변경부자재): ${judge.wkNm!}
<br><br>
접수담당자: ${judge.receUserNm!}
<br><br>
접수일자: ${judge.receYmd!}
<br><br>
심의분야: ${judge.rvFldNm!}
<br><br>
심의담당자: ${judge.rvFldMgrNm!}
<br><br>
신규 안전환경 사전심사가 접수등록 완료되고,  심의분야 “${judge.rvFldNm!}”의 심의담당자로 지정되었습니다.
아래 바로 가기를 클릭하여 사전심사 심의요청내용을 확인하고,  심의 후 심의결과를 등록 및 확정처리하시기 바랍니다.
