발의번호: ${chnage.safChngNo!}
<br><br>
발의부서/발의담당자: ${chnage.rqstDeptNm!} / ${chnage.rqstUserNm!}
<br><br>
발의일자: ${chnage.rqstDt!}
<br><br>
변경절차: ${chnage.chngAttNm!}
<br><br>
변경등급(발의): ${chnage.rqstMocLvlNm!}
<br><br>
변경요소: ${chnage.chngElem!}
<br><br>
접수부서/담당자: ${chnage.recevDeptNm!} / ${chnage.recevUserNm!}
<br><br>
검토항목: ${chnage.chkItmNm!}
<br><br>
검토담당자: ${chnage.chkUserNm!}
<br><br>
신규 변경 발의가 접수등록 완료되고, “${chnage.chkItmNm!}”의 검토담당자로 지정되었습니다.
아래 바로 가기를 클릭하여 변경 검토요청건을 확인하고 검토처리하시기 바랍니다.
