평가년도: ${workRiskEval02Prcs.evalYear!}
<br><br>
평가구분: ${workRiskEval02Prcs.evalTypeNm!}
<br><br>
평가계획기간: ${workRiskEval02Prcs.planPeriod!}
<br><br>
평가계획부서/담당자: ${workRiskEval02Prcs.mainDeptNm!} / ${workRiskEval02Prcs.mgrNm!}
<br><br>
평가명: ${workRiskEval02Prcs.evalNm!}
<br><br>
평가대상부서: ${workRiskEval02Prcs.deptNm!}
<br><br>
검토담당자: ${workRiskEval02Prcs.chkUserNm!}
<br><br>
평가대상부서의 작업위험성평가 결과가 검토 반려되었습니다.
<br>
아래 바로 가기를 클릭하여 평가대상부서의 평가결과를 다시 등록하고 결재요청하기 바랍니다.