평가년도: ${workRiskEval02Prcs.evalYear!}
<br><br>
평가구분: ${workRiskEval02Prcs.evalTypeNm!}
<br><br>
평가계획기간: ${workRiskEval02Prcs.planPeriod!}
<br><br>
평가계획부서/담당자: ${workRiskEval02Prcs.mainDeptNm!} / ${workRiskEval02Prcs.mgrNm!}
<br><br>
평가명: ${workRiskEval02Prcs.evalNm!}
<br><br>
평가대상부서: ${workRiskEval02Prcs.deptNm!}
<br><br>
평가대상부서의 작업위험성평가 결과가 등록되고 승인되었습니다.
<br>
아래 바로 가기를 클릭하여 평가대상부서의 평가결과를 확인하고 검토결과 등록 후 승인요청하기 바랍니다.