<table>
	<tr>
		<th style="width:20%;">사업장</th>
		<td style="width:30%;">${model.plantNm!}</td>
		<th style="width:20%;">평가년도</th>
		<td style="width:30%;">${model.evalYear!}</td>
	</tr>
	<tr>
		<th>평가구분</th>
		<td>${model.evalTypeNm!}</td>
		<th>평가계획기간</th>
		<td>${model.planPeriod!}</td>
	</tr>
	<tr>
		<th>평가계획부서</th>
		<td>${model.mainDeptNm!}</td>
		<th>평가계획담당자</th>
		<td>${model.mgrNm!}</td>
	</tr>
	<tr>
		<th>평가명</th>
		<td colspan="3">${model.evalNm!}</td>
	</tr>
</table>